modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="goose_hardtack"
version="${version}"
displayName="goose-hardtack"
authors="LuckGoose"
description='''
Standalone Goose Hardtack module split from GooseWorkshop.
'''

[[dependencies.goose_hardtack]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.goose_hardtack]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.goose_hardtack]]
modId="jei"
mandatory=false
versionRange="[15.0.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.goose_hardtack]]
modId="refinedstorage"
mandatory=false
versionRange="[1.12.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.goose_hardtack]]
modId="solcarrot"
mandatory=true
versionRange="[1.15,)"
ordering="AFTER"
side="BOTH"
